version: '3.8'

services:
  app:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: laravel_app
    ports:
      - 8000:8000
    volumes:
      - ./back:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tender
    volumes:
      - dbdata:/var/lib/mysql

  frontend:
    build:
      context: ./front
    container_name: next_frontend
    ports:
      - 3000:3000
    volumes:
      - ./front:/app
    command: npm run dev

volumes:
  dbdata:
