FROM php:8.2-fpm

WORKDIR /var/www/html

RUN apt-get update && apt-get install -y     zip unzip curl libpng-dev libonig-dev libxml2-dev     && docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd

COPY . .

RUN curl -sS https://getcomposer.org/installer | php &&     mv composer.phar /usr/local/bin/composer &&     composer install

CMD php artisan serve --host=0.0.0.0 --port=8000
